/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Clock: typeof import('./src/components/global/Clock.vue')['default']
    Gameboard: typeof import('./src/components/game/Gameboard.vue')['default']
    Graveyard: typeof import('./src/components/game/Graveyard.vue')['default']
    Header: typeof import('./src/components/global/Header.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
